---
title: Huxon Brewing
author: Joshua Brown
email: support@huxonbrewing.com
description: Huxon Brewing is a group of four friends who love brewing!
baseurl: huxonbrewing
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
