---
title: Huxon Brewing
author: Joshua Brown
email: support@forestry.io
description: Huxon Brewing is a group of four friends who love brewing!
baseurl: "#"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
